docker:
  image: yegor256/rultor-image:1.15.0
install: |-
  sudo tlmgr option repository ctan
  sudo gem install texsc:0.6.0
  sudo gem install texqc:0.6.0
  sudo tlmgr --verify-repo=none update --self
  sudo tlmgr --verify-repo=none update l3build docshots iexec
release:
  script: |-
    make VERSION=${tag} set-version
    git commit -am "version set to ${tag}"
    make
    echo 'y' | l3build upload --halt-on-error
