---
name: actionlint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v2
