name: latexmk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: yegor256/latexmk-action@master
        with:
          opts: -pdf ppt-slides.tex
          packages: libertine microtype fancyhdr href-ul minted fvextra framed tcolorbox environ catchfile xstring pgfopts crumbs qrcode varwidth lastpage anyfontsize fontsize changepage soul ifoddpage clicks textpos enumitem seqsplit ffcode titling pagecolor
